/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.ControladorRegistrarHistoriaClinica;
import modelos.HistoriaClinica;
import modelos.HistoriaClinicaDao;

/**
 *
 * @author Castulo
 */
public class VistaRegistrarHistoriaClinica extends javax.swing.JFrame {

     HistoriaClinica historiaClinica = new HistoriaClinica();
     HistoriaClinicaDao historiaClinicaDao = new HistoriaClinicaDao();
     
    
    public VistaRegistrarHistoriaClinica() {
        initComponents();
        setTitle("Registar Historia Clinica");
        setSize(1050,700);
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint();
         
        txt_idMascota.setVisible(false);
        ControladorRegistrarHistoriaClinica crhc = new ControladorRegistrarHistoriaClinica(historiaClinica, historiaClinicaDao,this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_anormalidades = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_dieta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea_anamnesis = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtArea_listaProblemas = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtArea_pronostico = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtArea_diagnostico = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtArea_planTerapeutico = new javax.swing.JTextArea();
        button_guardar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        button_modificar = new javax.swing.JButton();
        txt_idMascota = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Historia Clinica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel2.setText("Dieta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        txtArea_anormalidades.setColumns(20);
        txtArea_anormalidades.setRows(5);
        jScrollPane1.setViewportView(txtArea_anormalidades);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 240, 110));

        jLabel3.setText("Anamnesis:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtArea_dieta.setColumns(20);
        txtArea_dieta.setRows(5);
        jScrollPane2.setViewportView(txtArea_dieta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, 100));

        jLabel4.setText("Anormalidades:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        txtArea_anamnesis.setColumns(20);
        txtArea_anamnesis.setRows(5);
        jScrollPane3.setViewportView(txtArea_anamnesis);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 240, 100));

        jLabel5.setText("Lista Problemas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        txtArea_listaProblemas.setColumns(20);
        txtArea_listaProblemas.setRows(5);
        jScrollPane4.setViewportView(txtArea_listaProblemas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 250, 100));

        jLabel6.setText("Pronostico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, -1, -1));

        txtArea_pronostico.setColumns(20);
        txtArea_pronostico.setRows(5);
        jScrollPane5.setViewportView(txtArea_pronostico);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 250, 110));

        jLabel7.setText("Diagnostico:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        txtArea_diagnostico.setColumns(20);
        txtArea_diagnostico.setRows(5);
        jScrollPane6.setViewportView(txtArea_diagnostico);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 250, 100));

        jLabel8.setText("Plan terapeutico:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        txtArea_planTerapeutico.setColumns(20);
        txtArea_planTerapeutico.setRows(5);
        jScrollPane7.setViewportView(txtArea_planTerapeutico);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, -1, 100));

        button_guardar.setBackground(new java.awt.Color(51, 204, 255));
        button_guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_guardar.setForeground(new java.awt.Color(255, 255, 255));
        button_guardar.setText("Guardar");
        getContentPane().add(button_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        button_cancelar.setBackground(new java.awt.Color(51, 204, 255));
        button_cancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        button_cancelar.setText("Cancelar");
        getContentPane().add(button_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, -1, -1));

        button_modificar.setBackground(new java.awt.Color(51, 204, 255));
        button_modificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_modificar.setForeground(new java.awt.Color(255, 255, 255));
        button_modificar.setText("Modificar");
        getContentPane().add(button_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, -1, -1));
        getContentPane().add(txt_idMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistrarHistoriaClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistrarHistoriaClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton button_cancelar;
    public javax.swing.JButton button_guardar;
    public javax.swing.JButton button_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JTextArea txtArea_anamnesis;
    public javax.swing.JTextArea txtArea_anormalidades;
    public javax.swing.JTextArea txtArea_diagnostico;
    public javax.swing.JTextArea txtArea_dieta;
    public javax.swing.JTextArea txtArea_listaProblemas;
    public javax.swing.JTextArea txtArea_planTerapeutico;
    public javax.swing.JTextArea txtArea_pronostico;
    public javax.swing.JTextField txt_idMascota;
    // End of variables declaration//GEN-END:variables
}
