/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.ControladorMenu;

/**
 *
 * @author Castulo
 */
public class VistaMenu extends javax.swing.JFrame {

  
   VistaEstetica vistaEstetica = new VistaEstetica();
   VistaConsulta vistaConsulta = new VistaConsulta();
   VistaRegistrarClienteyMascota vrcm = new VistaRegistrarClienteyMascota();
   VistaVeterinarios vistaVeterinarios = new VistaVeterinarios();
   VistaHistoriaClinica vistaHistoriaClinica = new VistaHistoriaClinica();
   VistaVacuna_Desparasitacion vistaVacuna_Desparasitacion = new VistaVacuna_Desparasitacion();
   VistaAgendarCita vistaAgendarCita = new VistaAgendarCita();
   VistaReporte vistaReporte = new VistaReporte();
   
    public VistaMenu() {
        initComponents();
        setTitle("Menu");
        setSize(850,500);
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint();
        
        ControladorMenu cm = new ControladorMenu(this, vistaEstetica, vistaConsulta, vrcm, vistaVeterinarios, vistaHistoriaClinica, 
                vistaVacuna_Desparasitacion, vistaAgendarCita, vistaReporte);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_registrarMascota_Cliente = new javax.swing.JPanel();
        label_registarMascota_Cliente = new javax.swing.JLabel();
        panel_historiaClinica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_consultas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panel_estetica = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        panel_agendarCitas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_vacunacion_desparacitacion = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel_reportes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        panel_veterinarios = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_registrarMascota_Cliente.setBackground(new java.awt.Color(51, 102, 255));
        panel_registrarMascota_Cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_registarMascota_Cliente.setBackground(new java.awt.Color(0, 0, 0));
        label_registarMascota_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        label_registarMascota_Cliente.setText("Registrar Mascota-Cliente");
        panel_registrarMascota_Cliente.add(label_registarMascota_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 147, 68));

        jPanel1.add(panel_registrarMascota_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 180, 70));

        panel_historiaClinica.setBackground(new java.awt.Color(51, 102, 255));
        panel_historiaClinica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historia Clinica");
        panel_historiaClinica.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 120, 68));

        jPanel1.add(panel_historiaClinica, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 180, 70));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        panel_consultas.setBackground(new java.awt.Color(51, 102, 255));
        panel_consultas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultas");
        panel_consultas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jPanel1.add(panel_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 180, 70));

        panel_estetica.setBackground(new java.awt.Color(51, 102, 255));
        panel_estetica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(51, 102, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Estetica");
        panel_estetica.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jPanel1.add(panel_estetica, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 180, 70));

        panel_agendarCitas.setBackground(new java.awt.Color(51, 102, 255));
        panel_agendarCitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Agendar citas");
        panel_agendarCitas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 40));

        jPanel1.add(panel_agendarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 180, 70));

        panel_vacunacion_desparacitacion.setBackground(new java.awt.Color(51, 102, 255));
        panel_vacunacion_desparacitacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vacunacion y Desparacitación ");
        panel_vacunacion_desparacitacion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jPanel1.add(panel_vacunacion_desparacitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 180, 70));

        panel_reportes.setBackground(new java.awt.Color(51, 102, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Reportes");

        javax.swing.GroupLayout panel_reportesLayout = new javax.swing.GroupLayout(panel_reportes);
        panel_reportes.setLayout(panel_reportesLayout);
        panel_reportesLayout.setHorizontalGroup(
            panel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportesLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        panel_reportesLayout.setVerticalGroup(
            panel_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reportesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(panel_reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 180, 70));

        panel_veterinarios.setBackground(new java.awt.Color(51, 102, 255));

        jLabel5.setBackground(new java.awt.Color(51, 102, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Veterinarios");

        javax.swing.GroupLayout panel_veterinariosLayout = new javax.swing.GroupLayout(panel_veterinarios);
        panel_veterinarios.setLayout(panel_veterinariosLayout);
        panel_veterinariosLayout.setHorizontalGroup(
            panel_veterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_veterinariosLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        panel_veterinariosLayout.setVerticalGroup(
            panel_veterinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_veterinariosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(panel_veterinarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 180, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_registarMascota_Cliente;
    public javax.swing.JPanel panel_agendarCitas;
    public javax.swing.JPanel panel_consultas;
    public javax.swing.JPanel panel_estetica;
    public javax.swing.JPanel panel_historiaClinica;
    public javax.swing.JPanel panel_registrarMascota_Cliente;
    public javax.swing.JPanel panel_reportes;
    public javax.swing.JPanel panel_vacunacion_desparacitacion;
    public javax.swing.JPanel panel_veterinarios;
    // End of variables declaration//GEN-END:variables
}
