/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Controladores.ControladorBuscarCliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import modelos.Cliente;
import modelos.ClienteDao;
import modelos.Conexion;


public class VistaBuscarCliente extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    ClienteDao clienteDao = new ClienteDao();
  
    public VistaBuscarCliente() {
        initComponents();
        setTitle("Buscar Cliente");
        setSize(800,500);
        setResizable(false);
        setLocationRelativeTo(null);
        this.repaint();
        ControladorBuscarCliente cbc = new ControladorBuscarCliente(cliente, clienteDao, this);
        cbc.listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_cliente = new javax.swing.JComboBox<>();
        txt_buscarCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cliente = new javax.swing.JTable();
        button_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Buscar Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Seleccione como desea buscar:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 77, -1, 40));

        cmb_cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Dni" }));
        jPanel1.add(cmb_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 130, 30));
        jPanel1.add(txt_buscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 150, 30));

        table_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Documento", "Nombre", "Apellidos", "Celular", "Correo Electronico"
            }
        ));
        table_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_cliente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 670, 270));

        button_buscar.setBackground(new java.awt.Color(51, 204, 255));
        button_buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_buscar.setForeground(new java.awt.Color(255, 255, 255));
        button_buscar.setText("Buscar");
        jPanel1.add(button_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clienteMouseClicked
       
    }//GEN-LAST:event_table_clienteMouseClicked
    Conexion conexion = new Conexion();
    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    public void buscarCliente(JComboBox<String> comboBox) {
        String query = "SELECT * FROM cliente AS cli";
         
        if (comboBox.getSelectedItem().equals("Nombre")) {
            String nombreBuscado = txt_buscarCliente.getText();
            if (!nombreBuscado.isEmpty()) {
                query += " WHERE cli.nombre LIKE ?";
            }
        } else if (comboBox.getSelectedItem().equals("Dni")) {
            String dniBuscado = txt_buscarCliente.getText();
            if (!dniBuscado.isEmpty()) {
                query += " WHERE cli.dni = ?";
            }
        }

        try {
            conn = conexion.getConnection();
            pst = conn.prepareStatement(query);

            if (comboBox.getSelectedItem().equals("Nombre")) {
                String nombreBuscado = txt_buscarCliente.getText();
                if (!nombreBuscado.isEmpty()) {
                    pst.setString(1, "%" + nombreBuscado + "%");
                }
            } else if (comboBox.getSelectedItem().equals("Dni")) {
                String dniBuscado = txt_buscarCliente.getText();
                if (!dniBuscado.isEmpty()) {
                    pst.setString(1, dniBuscado);
                }
            }

            rs = pst.executeQuery();

            
            DefaultTableModel model = (DefaultTableModel) table_cliente.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getString("dni");
                row[1] = rs.getString("nombre");
                row[2] = rs.getString("apellido");
                row[3] = rs.getString("celular");
                row[4] = rs.getString("correo_electronico");
                model.addRow(row);
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBuscarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBuscarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton button_buscar;
    public javax.swing.JComboBox<String> cmb_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable table_cliente;
    public javax.swing.JTextField txt_buscarCliente;
    // End of variables declaration//GEN-END:variables
}
